spring:
  profiles:
    active: "local"
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # camel case -> underscore
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl # 컬럼, 테이블명 커스텀하게 사용 가능
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 50